project:
  type: website

website:
  title: "felixruntime"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



